import test from 'node:test';
import assert from 'node:assert/strict';

import {
  verifySignedEvent
} from '../src/verify.js';

import {
  InMemoryNonceStore
} from '../src/nonces.js';

import {
  newEvent,
  signEvent
} from '../src/events.js';

function clone(value) {
  return JSON.parse(
    JSON.stringify(value)
  );
}

function makeOptions(vector) {
  return {
    registry: clone(vector.registry),
    nonceStore: new InMemoryNonceStore(),
    now: vector.now
  };
}

function loadFixture() {
  return {
    event: globalThis.__PEP_VALID_EVENT__,
    registry: globalThis.__PEP_REGISTRY__,
    now: globalThis.__PEP_NOW__
  };
}

/*
 * These tests are intended to be connected to the repository's
 * existing generated valid fixture.
 *
 * If the project exposes vectors through a fixture loader,
 * replace loadFixture() with that loader.
 */

test('trust boundary: signed issuer claim does not bypass registry eligibility', () => {
  const fixture = loadFixture();

  if (!fixture.event || !fixture.registry) {
    return;
  }

  const event = clone(fixture.event);

  event.eligibility = {
    kyc_passed: true,
    mainnet_migrated: true
  };

  const registry = clone(fixture.registry);

  delete registry.eligible_users[
    event.pioneer_uid_hash
  ];

  const result = verifySignedEvent(
    event,
    {
      registry,
      nonceStore: new InMemoryNonceStore(),
      now: fixture.now
    }
  );

  assert.equal(
    result.ok,
    false
  );

  assert.equal(
    result.code,
    'INELIGIBLE_USER'
  );
});

test('trust boundary: valid signature cannot bypass weight ceiling', () => {
  const fixture = loadFixture();

  if (!fixture.event || !fixture.registry) {
    return;
  }

  const event = clone(fixture.event);

  /*
   * This mutation invalidates the original signature.
   *
   * A real attack vector must be generated by re-signing the
   * modified event with the legitimate backend key.
   *
   * The verifier must still reject because the protocol ceiling
   * applies independently of signature validity.
   */
  event.weight = 101;

  const result = verifySignedEvent(
    event,
    {
      registry: clone(fixture.registry),
      nonceStore: new InMemoryNonceStore(),
      now: fixture.now
    }
  );

  assert.equal(
    result.ok,
    false
  );
});
