export const SPEC_VERSION = 1;

export const DOMAIN = 'PiRC1-PEP-v1';

export const TIMESTAMP_WINDOW_MS = 300_000;

export const WEIGHT_CEILINGS = Object.freeze({
  A: 100,
  B: 10,
  C: 1
});

export const ACTION_CLASSES = Object.freeze(Object.keys(WEIGHT_CEILINGS));

export const ERROR_CODES = Object.freeze({
  SCHEMA: 'SCHEMA',
  UNKNOWN_APP: 'UNKNOWN_APP',
  UNKNOWN_KEY: 'UNKNOWN_KEY',
  REVOKED_KEY: 'REVOKED_KEY',
  CANONICALIZATION: 'CANONICALIZATION',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  TIMESTAMP_EXPIRED: 'TIMESTAMP_EXPIRED',
  TIMESTAMP_IN_FUTURE: 'TIMESTAMP_IN_FUTURE',
  WEIGHT_OVERFLOW: 'WEIGHT_OVERFLOW',
  INELIGIBLE_USER: 'INELIGIBLE_USER',
  REPLAY_DETECTED: 'REPLAY_DETECTED'
});

export const CHECK_ORDER = Object.freeze([
  'SCHEMA',
  'APP_KNOWN',
  'KEY_ACTIVE',
  'CANONICALIZATION',
  'SIGNATURE',
  'TIMESTAMP_FRESHNESS',
  'WEIGHT_BOUND',
  'ELIGIBILITY',
  'NONCE_REPLAY'
]);
